"""Preset library, part 2: the rest of the genre taxonomy.

Same authoring rule as presets_core.py - name the signature, not the
ingredients. See that module's docstring.
"""

P2 = [
    # ------------------------------------------------------------- electronic
    ("electronic", "house", "Electronic / House", 124, "A minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["house"], ["hypnotic and trance-like"], ["a crowded dancefloor at peak hour"],
     ["warm club system mix", "long patient builds"],
     ["four-on-the-floor kick with open hats on the offbeat", "filtered disco sample loop",
      "shuffled sixteenth hi-hats", "stabbing piano chords", "soulful chopped vocal sample"],
     ("wordless", ["soulful gospel-trained voice"], ["a single sampled phrase looped and filtered"])),
    ("electronic", "techno", "Electronic / Dark Techno", 132, "A minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["techno"], ["dark and brooding"], ["an after-hours club"],
     ["relentless and hypnotic", "long filter sweeps", "industrial space"],
     ["unchanging driving kick", "rumbling distorted sub", "metallic percussion loop",
      "gradual filter opening over sixteen bars", "no melody, only texture"],
     ("instrumental", [], [])),
    ("electronic", "dnb", "Electronic / Drum & Bass", 174, "F minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["drum and bass"], ["urgent and restless"], ["a crowded dancefloor at peak hour", "running and cardio"],
     ["tight and fast", "sub-heavy on a club system"],
     ["chopped and rearranged breakbeat", "growling modulated reese bass", "half-time feel against fast drums",
      "sharp snare on the two and four", "a drop stripping back to drums and bass"],
     ("instrumental", [], [])),
    ("electronic", "synthwave", "Electronic / Synthwave", 112, "F# minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["synthwave"], ["warm and nostalgic"], ["a long night drive"],
     ["1980s analog warmth", "huge gated reverb", "tape saturation"],
     ["pulsing analog bass arpeggio", "gated snare with enormous reverb", "saw-wave lead melody",
      "neon-bright pad chords", "slow filter sweep through the build"],
     ("instrumental", [], [])),
    ("electronic", "ambient", "Electronic / Ambient Drift", 62, "D major", "simple diatonic", "loose and human", "harmonically led", "light low end",
     ["ambient electronic"], ["calm and meditative"], ["falling asleep and winding down", "meditation and yoga"],
     ["vast reverb", "no percussion at all", "very slow movement"],
     ["slowly evolving pad textures", "granular shimmer", "distant field recordings",
      "single sustained piano notes with long decay", "no drums"],
     ("instrumental", [], [])),
    ("electronic", "trip_hop", "Electronic / Trip-Hop", 88, "C minor", "moderately extended", "loose and human", "balanced", "deep sub-heavy low end",
     ["trip-hop"], ["dark and brooding"], ["an after-hours club", "rainy-day headphones listening"],
     ["dusty and low-passed", "cavernous reverb", "cinematic weight"],
     ["slow heavy dusty breakbeat", "dub-style bass with long decay", "cinematic minor string sample",
      "vinyl crackle throughout", "sparse detuned Rhodes"],
     ("sung", ["light breathy voice"], ["sung low and close, almost spoken", "drenched in delay"])),
    ("electronic", "italo_disco", "Electronic / Italo-Disco", 126, "D minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["italo-disco"], ["euphoric and rushing"], ["a crowded dancefloor at peak hour"],
     ["bright analog sheen", "generous reverb on everything"],
     ["octave-jumping synth bassline", "drum machine claps on the backbeat", "sparkling arpeggio",
      "vocoder counter-melody", "simple repeated synth hook"],
     ("sung", ["clear bright voice"], ["sung with earnest melodrama", "vocoded answering phrases"])),
    ("electronic", "nu_disco", "Electronic / Nu-Disco", 118, "F# minor", "moderately extended", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["nu-disco"], ["playful and carefree"], ["a crowded dancefloor at peak hour"],
     ["clean modern polish", "sidechain pump under the kick"],
     ["filtered funk guitar riff", "popping disco bassline", "four-on-the-floor with live-feel hats",
      "sweeping disco strings", "handclaps layered on the backbeat"],
     ("sung", ["soulful gospel-trained voice"], ["crooned over the groove", "falsetto hook"])),
    ("electronic", "eurobeat", "Electronic / Eurobeat", 155, "B minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["eurobeat"], ["euphoric and rushing"], ["a long night drive"],
     ["maximum energy, no space", "loud and bright"],
     ["hyper-fast octave bassline", "relentless sixteenth arpeggio", "huge anthemic chorus hook",
      "crash on every bar", "breakdown and rebuild before the final chorus"],
     ("sung", ["powerful belting voice"], ["belted at full power throughout"])),
    ("electronic", "electropop", "Electronic / Electropop", 112, "C minor", "simple diatonic", "machine-tight", "balanced", "solid bass weight",
     ["electropop"], ["bittersweet"], ["a long night drive"],
     ["clean modern mix", "heavy sidechain on the pads"],
     ["punchy programmed drums", "detuned synth bass", "vocoded harmony stack",
      "plucked synth counter-melody", "filtered build into the chorus"],
     ("sung", ["clear bright voice"], ["sung with processed precision", "pitch-corrected as an effect"])),
    ("electronic", "folktronica", "Electronic / Folktronica", 100, "D major", "simple diatonic", "loose and human", "balanced", "moderate low end",
     ["folktronica"], ["hazy and drifting"], ["a slow lazy Sunday morning"],
     ["warm and organic", "acoustic sources digitally chopped"],
     ["chopped and stuttered acoustic guitar", "glitchy clicks and cuts percussion",
      "warm analog pad bed", "field recordings woven in", "glockenspiel melody"],
     ("sung", ["light breathy voice"], ["sung softly and close", "layered into texture"])),
    ("electronic", "dark_ambient", "Electronic / Dark Ambient", 60, "C minor", "chromatic / extended harmony", "loose and human", "harmonically led", "deep sub-heavy low end",
     ["dark ambient"], ["haunting and eerie"], ["a tense chase scene"],
     ["oppressive and cavernous", "almost no high end"],
     ["low drone bed", "distant metallic scrapes", "sub-bass rumble",
      "no discernible beat", "occasional dissonant swell"],
     ("instrumental", [], [])),
    ("electronic", "alternative_dance", "Electronic / Alternative Dance", 122, "A minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["alternative dance"], ["mysterious and shadowy"], ["an after-hours club"],
     ["cold and dry", "post-punk edge over a dance beat"],
     ["motorik four-on-the-floor", "driving post-punk bassline high in the mix",
      "angular clean guitar stabs", "cold analog synth sequence", "minimal verses opening into the chorus"],
     ("sung", ["deep resonant low-register voice"], ["sung in a detached monotone", "obsessive repeated hook"])),
    ("electronic", "dance_punk", "Electronic / Dance-Punk", 138, "E minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["dance-punk"], ["energetic and driving"], ["a festival main stage"],
     ["dry and punchy", "raw but danceable"],
     ["disco beat played on a live kit", "cowbell on the offbeat", "angular scratchy guitar",
      "distorted bass carrying the riff", "shouted call-and-response"],
     ("sung", ["nasal indie voice"], ["shouted and yelped", "whole-band chant on the hook"])),
    # -------------------------------------------------------------- acoustic
    ("acoustic", "indie_folk", "Acoustic / Indie Folk", 96, "G major", "simple diatonic", "loose and human", "harmonically led", "moderate low end",
     ["indie folk"], ["tender and intimate"], ["a campfire singalong", "a slow lazy Sunday morning"],
     ["close-mic'd and dry", "audible fingers on strings and breath"],
     ["fingerpicked acoustic guitar", "brushed snare keeping time", "upright bass underneath",
      "mandolin or banjo doubling the melody", "whole-room group harmony on the chorus"],
     ("sung", ["warm husky voice"], ["sung quietly and close to the mic", "a second voice joining in thirds"])),
    ("acoustic", "country", "Acoustic / Country", 104, "D major", "simple diatonic", "loose and human", "balanced", "solid bass weight",
     ["country"], ["warm and nostalgic"], ["a summer road trip"],
     ["clean Nashville studio sound", "vocals right up front"],
     ["crying pedal steel guitar", "twangy Telecaster licks between lines", "brushed snare with a train-beat feel",
      "fiddle answering the vocal", "walking bass on the turnaround"],
     ("sung", ["warm husky voice"], ["sung with a storyteller's phrasing", "close harmony on the chorus"])),
    ("acoustic", "bluegrass", "Acoustic / Bluegrass", 140, "A major", "simple diatonic", "loose and human", "harmonically led", "moderate low end",
     ["bluegrass"], ["playful and carefree"], ["a campfire singalong"],
     ["recorded live around one microphone", "no drums at all"],
     ["rolling three-finger banjo", "chopping mandolin on the backbeat", "fiddle taking the break",
      "slapped upright bass", "instruments trading solos in turn"],
     ("sung", ["clear bright voice"], ["high lonesome tenor above the melody", "three-part harmony on the chorus"])),
    ("acoustic", "solo_piano", "Acoustic / Solo Piano", 68, "F major", "moderately extended", "loose and human", "harmonically led", "light low end",
     ["solo piano"], ["reflective and quiet"], ["falling asleep and winding down", "a funeral or memorial"],
     ["close-mic'd with audible hammers and pedal", "natural room decay"],
     ["one grand piano and nothing else", "sustain pedal blurring the harmony",
      "rubato phrasing that breathes", "sparse left hand", "long silences between phrases"],
     ("instrumental", [], [])),
    # ------------------------------------------------------------------ jazz
    ("jazz", "jazz_trio", "Jazz / Late-Night Trio", 120, "Bb major", "chromatic / extended harmony", "loose and human", "balanced", "solid bass weight",
     ["jazz"], ["reflective and quiet"], ["a cocktail lounge evening"],
     ["one room, minimal miking", "warm and unhurried"],
     ["walking upright bass", "brushed ride cymbal keeping time", "comping piano with rootless voicings",
      "each player soloing in turn", "trading fours before the head returns"],
     ("instrumental", [], [])),
    ("jazz", "cool_jazz", "Jazz / Cool Jazz", 96, "D minor", "chromatic / extended harmony", "loose and human", "harmonically led", "moderate low end",
     ["cool jazz"], ["calm and meditative"], ["a cocktail lounge evening"],
     ["dry and intimate", "restrained dynamics throughout"],
     ["muted trumpet stating the melody", "relaxed swing that never pushes", "sparse piano comping",
      "soft brushed drums", "long unhurried phrases"],
     ("instrumental", [], [])),
    ("jazz", "bossa_nova", "Jazz / Bossa Nova", 130, "A minor", "chromatic / extended harmony", "loose and human", "harmonically led", "moderate low end",
     ["bossa nova"], ["romantic and longing"], ["a beach party", "a romantic dinner"],
     ["dry and close", "gentle throughout, never loud"],
     ["syncopated nylon-string guitar pattern", "soft rim-click keeping the clave",
      "shaker underneath", "flute or muted trumpet on the melody", "seventh and ninth chords throughout"],
     ("sung", ["light breathy voice"], ["sung almost under the breath", "lagging just behind the beat"])),
    ("jazz", "blues", "Jazz / Slow Blues", 72, "E major", "moderately extended", "loose and human", "balanced", "solid bass weight",
     ["blues"], ["melancholy and wistful"], ["a cocktail lounge evening"],
     ["live in a small room", "warm valve amp saturation"],
     ["twelve-bar form with a turnaround", "shuffle feel on the ride", "bent and vibratoed guitar phrases",
      "Hammond organ underneath", "call and response between voice and guitar"],
     ("sung", ["gritty rasping voice"], ["moaned and drawn out", "guitar answering every sung line"])),
    ("jazz", "jazz_funk", "Jazz / Jazz-Funk", 108, "E minor", "chromatic / extended harmony", "loose and human", "drum-forward", "solid bass weight",
     ["jazz-funk"], ["confident and swaggering"], ["a crowded dancefloor at peak hour"],
     ["punchy and dry", "live band locked together"],
     ["wah clavinet riff", "popping slap bass", "tight syncopated horn hits",
      "Rhodes comping over a vamp", "extended instrumental solo section"],
     ("instrumental", [], [])),
    ("jazz", "afro_jazz", "Jazz / Afro-Jazz", 112, "F minor", "moderately extended", "loose and human", "drum-forward", "solid bass weight",
     ["afro-jazz"], ["hypnotic and trance-like"], ["a festival main stage"],
     ["live and open", "percussion wide across the stereo field"],
     ["interlocking polyrhythmic percussion", "repeating modal horn riff", "one-chord vamp that never resolves",
      "call-and-response horns", "long building solo over the groove"],
     ("sung", ["powerful belting voice"], ["chanted call answered by the group"])),
    # ----------------------------------------------------------------- swing
    ("swing", "big_band", "Swing / Big Band", 168, "Bb major", "moderately extended", "loose and human", "drum-forward", "solid bass weight",
     ["big band swing"], ["playful and carefree"], ["a cocktail lounge evening"],
     ["recorded live as a full band", "brass wide and forward"],
     ["walking upright bass", "ride cymbal driving the swing", "punchy full brass section stabs",
      "call-and-response between brass and reeds", "a shout chorus before the final head"],
     ("sung", ["smoky jazz-club voice"], ["crooned in front of the band", "band answering each phrase"])),
    ("swing", "dixieland", "Swing / Dixieland", 200, "F major", "simple diatonic", "loose and human", "drum-forward", "moderate low end",
     ["dixieland"], ["playful and carefree"], ["a campfire singalong"],
     ["one-room live recording", "narrow vintage image"],
     ["collective improvisation with everyone soloing at once", "trumpet carrying the lead",
      "clarinet weaving counter-melody above", "trombone sliding underneath", "banjo and tuba keeping time"],
     ("instrumental", [], [])),
    ("swing", "boogie_woogie", "Swing / Boogie Woogie", 176, "C major", "simple diatonic", "loose and human", "balanced", "solid bass weight",
     ["boogie woogie"], ["playful and carefree"], ["a cocktail lounge evening"],
     ["single room, single microphone", "vintage and raw"],
     ["rolling eight-to-the-bar left-hand bass figure", "right-hand blues licks against it",
      "shuffle throughout", "twelve-bar form", "piano carrying everything"],
     ("sung", ["gritty rasping voice"], ["shouted over the piano"])),
    ("swing", "jump_blues", "Swing / Jump Blues", 160, "G major", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["jump blues"], ["confident and swaggering"], ["a crowded dancefloor at peak hour"],
     ["live and hot", "horns pushed to the edge"],
     ["honking tenor saxophone solo", "slapped upright bass", "boogie piano underneath",
      "shuffle on the ride cymbal", "riffing horn section behind the vocal"],
     ("sung", ["powerful belting voice"], ["shouted with showmanship", "crowd-response hooks"])),
    # ------------------------------------------------------------------ world
    ("world", "reggae", "World / Reggae", 76, "G major", "simple diatonic", "loose and human", "balanced", "solid bass weight",
     ["reggae"], ["laid-back and dreamy"], ["a beach party", "a slow lazy Sunday morning"],
     ["spring reverb and dub delay throws", "bass enormous and round", "spacious mix"],
     ["offbeat guitar skank on the upstroke", "one-drop drums with the kick on the three",
      "deep melodic round bassline", "Hammond organ bubble", "delay throws on the end of phrases"],
     ("sung", ["warm mid-range voice"], ["sung lazily behind the beat", "harmony trio answering the lines"])),
    ("world", "afrobeats", "World / Afrobeats", 104, "F major", "simple diatonic", "loose and human", "drum-forward", "deep sub-heavy low end",
     ["afrobeats"], ["playful and carefree"], ["a beach party", "a crowded dancefloor at peak hour"],
     ["clean modern polish", "percussion wide and bright"],
     ["syncopated log-drum bass pattern", "shaker and woodblock through every bar",
      "clean guitar riff looping", "sparse arrangement with lots of space", "vocal ad-libs as percussion"],
     ("sung", ["warm mid-range voice"], ["sung with a relaxed melodic lilt", "pidgin ad-libs between lines"])),
    ("world", "latin_pop", "World / Latin Pop", 96, "A minor", "moderately extended", "loose and human", "drum-forward", "solid bass weight",
     ["latin pop"], ["romantic and longing"], ["a beach party", "a crowded dancefloor at peak hour"],
     ["bright modern mix", "percussion layered wide"],
     ["montuno piano figure", "congas and timbales", "brass section stabs",
      "clave pattern underneath", "tumbao bass locking with the congas"],
     ("sung", ["warm husky voice"], ["sung with passionate vibrato", "coro answering the lead"])),
    ("world", "bachata", "World / Bachata", 128, "B minor", "moderately extended", "loose and human", "balanced", "solid bass weight",
     ["bachata"], ["romantic and longing"], ["a romantic dinner"],
     ["clean and bright", "guitars wide, percussion close"],
     ["arpeggiated lead guitar with heavy reverb", "bongo martillo pattern", "güira scraping sixteenths",
      "syncopated bass on the offbeat", "four-count hip accent on the last beat"],
     ("sung", ["warm husky voice"], ["sung with pleading emotion", "close harmony on the refrain"])),
    ("world", "bhangra", "World / Bhangra", 140, "D minor", "simple diatonic", "loose and human", "drum-forward", "deep sub-heavy low end",
     ["bhangra"], ["euphoric and rushing"], ["a wedding first dance", "a crowded dancefloor at peak hour"],
     ["loud and celebratory", "drums enormous"],
     ["dhol drum driving the whole track", "tumbi plucking a repeated high figure",
      "chanted hooks", "modern sub-bass under the dhol", "handclaps and shouts"],
     ("sung", ["powerful belting voice"], ["chanted with full-throated energy", "crowd shouts answering"])),
    ("world", "flamenco", "World / Flamenco", 110, "A minor", "chromatic / extended harmony", "loose and human", "drum-forward", "moderate low end",
     ["flamenco"], ["gritty and raw"], ["a festival main stage"],
     ["close and dry", "handclaps wide in the room"],
     ["rasgueado strummed nylon guitar", "palmas handclaps carrying the compás",
      "cajón keeping the rhythm", "phrygian cadence throughout", "sudden stops and restarts"],
     ("sung", ["strained emotional voice"], ["wailed with raw ornamented melisma", "shouts of encouragement between phrases"])),
    ("world", "arabic_pop", "World / Arabic Pop", 100, "D minor", "chromatic / extended harmony", "loose and human", "drum-forward", "deep sub-heavy low end",
     ["arabic pop"], ["sensual and smouldering"], ["a romantic dinner"],
     ["modern polish over traditional instruments", "strings wide and lush"],
     ["oud melody with quarter-tone bends", "darbuka rhythm pattern", "unison string ensemble line",
      "riq tambourine", "modern beat under traditional melody"],
     ("sung", ["warm husky voice"], ["sung with ornamented melisma", "long held notes over the strings"])),
    # ---------------------------------------------------------------- vocal
    ("vocal", "barbershop", "Vocal / Barbershop Quartet", 120, "Ab major", "moderately extended", "loose and human", "harmonically led", "light low end",
     ["barbershop"], ["playful and carefree"], ["a wedding first dance"],
     ["completely unaccompanied", "close vintage mono image"],
     ["four voices and no instruments at all", "lead, tenor above, baritone and bass",
      "ringing close-harmony chords", "swipes and tag endings", "finger snaps only"],
     ("sung", ["choir of many voices"], ["four-part close harmony throughout", "held tag chord at the end"])),
    # --------------------------------------------------------------- country
    ("country", "honky_tonk", "Country / Honky Tonk", 132, "A major", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["honky tonk"], ["playful and carefree"], ["a campfire singalong"],
     ["live bar-room sound", "vintage and narrow"],
     ["crying pedal steel", "shuffle rhythm with brushed snare", "walking upright bass",
      "twangy Telecaster solo", "barroom piano fills"],
     ("sung", ["warm husky voice"], ["sung with a hard country twang", "close harmony on the chorus"])),
    # -------------------------------------------------------------- cinematic
    ("cinematic", "epic_trailer", "Cinematic / Epic Trailer", 92, "D minor", "simple diatonic", "steady", "drum-forward", "deep sub-heavy low end",
     ["epic trailer"], ["epic and cinematic"], ["a film's emotional climax", "a video game boss fight"],
     ["enormous dynamic range", "sub drops on every impact", "vast hall reverb"],
     ["staccato ostinato strings", "taiko and war drums", "brass braams",
      "wordless choir on the final hit", "silence before the last impact"],
     ("wordless", ["choir of many voices"], ["wordless massed choir"])),
    ("cinematic", "orchestral", "Cinematic / Orchestral Score", 76, "C major", "moderately extended", "loose and human", "harmonically led", "moderate low end",
     ["orchestral score"], ["reflective and quiet"], ["a film's emotional climax"],
     ["recorded in a concert hall", "natural dynamics, no compression"],
     ["string section carrying the theme", "solo woodwind answering", "harp arpeggios underneath",
      "no drum kit", "theme restated by full orchestra at the climax"],
     ("instrumental", [], [])),
    ("cinematic", "horror", "Cinematic / Horror Tension", 60, "C minor", "chromatic / extended harmony", "loose and human", "harmonically led", "deep sub-heavy low end",
     ["horror score"], ["haunting and eerie"], ["a tense chase scene"],
     ["oppressive and close", "sudden extreme dynamic jumps"],
     ["dissonant clustered strings", "prepared piano and scraped strings", "sub-bass drone underneath",
      "sudden stinger hits", "long silences that build dread"],
     ("instrumental", [], [])),
    ("cinematic", "classical", "Cinematic / Classical Chamber", 92, "D major", "chromatic / extended harmony", "loose and human", "harmonically led", "light low end",
     ["chamber music"], ["tender and intimate"], ["a romantic dinner", "a funeral or memorial"],
     ["small hall acoustic", "no processing at all"],
     ["string quartet with each voice audible", "counterpoint between the parts",
      "solo cello taking the melody", "no percussion", "rubato phrasing"],
     ("instrumental", [], [])),
]
