"""Second wave of presets: genres from the YuE2 taxonomy.

map-yue2.github.io lists 70 genres across 6 languages; the original library
reached about half of them. These fill the gap, written to the same schema so
both output formats work identically across the whole library.

Imported by tools/make_presets.py.
"""

P2 = [
    ("swing", "big_band", "Swing / Big Band", 168, "Bb major", "moderately extended", "loose and human", "drum-forward", "solid bass weight",
     ["big band", "swing"], ["playful and carefree", "bright and joyful"], ["a cocktail lounge evening"],
     ["a raw live-room recording", "warm analog tape saturation"],
     ["brass section", "saxophone", "upright double bass", "brushed jazz drums", "grand piano"],
     ("sung", ["a smoky jazz-club voice"], ["crooned smoothly", "answered by a call-and-response choir"])),
    ("swing", "dixieland", "Swing / Dixieland", 200, "F major", "simple diatonic", "loose and human", "drum-forward", "moderate low end",
     ["dixieland", "jazz"], ["playful and carefree", "euphoric and rushing"], ["a campfire singalong"],
     ["a raw live-room recording", "a narrow mono-leaning image"],
     ["solo trumpet", "clarinet", "upright double bass", "acoustic drum kit", "honky-tonk piano"],
     ("instrumental", [], [])),
    ("swing", "boogie_woogie", "Swing / Boogie Woogie", 176, "C major", "simple diatonic", "loose and human", "balanced", "solid bass weight",
     ["boogie woogie", "blues"], ["playful and carefree", "energetic and driving"], ["a cocktail lounge evening"],
     ["a raw live-room recording", "warm analog tape saturation"],
     ["honky-tonk piano", "upright double bass", "acoustic drum kit", "saxophone"],
     ("sung", ["a gritty rasping voice"], ["belted out powerfully"])),
    ("swing", "jump_blues", "Swing / Jump Blues", 160, "G major", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["jump blues", "blues"], ["confident and swaggering", "bright and joyful"], ["a crowded dancefloor at peak hour"],
     ["a raw live-room recording", "warm analog tape saturation"],
     ["saxophone", "brass section", "upright double bass", "honky-tonk piano", "acoustic drum kit"],
     ("sung", ["a powerful belting voice"], ["belted out powerfully", "answered by a call-and-response choir"])),
    ("jazz", "cool_jazz", "Jazz / Cool Jazz", 96, "D minor", "chromatic / extended harmony", "loose and human", "harmonically led", "moderate low end",
     ["cool jazz", "jazz"], ["calm and meditative", "reflective and quiet"], ["a cocktail lounge evening"],
     ["a dry close-mic'd intimate sound", "warm analog tape saturation"],
     ["saxophone", "muted trumpet", "upright double bass", "brushed jazz drums", "grand piano"],
     ("instrumental", [], [])),
    ("jazz", "jazz_funk", "Jazz / Jazz-Funk", 108, "E minor", "chromatic / extended harmony", "loose and human", "drum-forward", "solid bass weight",
     ["jazz fusion", "funk"], ["confident and swaggering", "playful and carefree"], ["a crowded dancefloor at peak hour"],
     ["a crisp studio multitrack production", "warm analog tape saturation"],
     ["warm Rhodes electric piano", "slap bass", "acoustic drum kit", "saxophone", "clean electric guitar"],
     ("instrumental", [], [])),
    ("jazz", "afro_jazz", "Jazz / Afro-Jazz", 112, "F minor", "moderately extended", "loose and human", "drum-forward", "solid bass weight",
     ["jazz fusion", "world fusion"], ["playful and carefree", "hypnotic and trance-like"], ["a festival main stage"],
     ["a raw live-room recording", "a wide spacious stereo image"],
     ["congas and bongos", "saxophone", "electric bass guitar", "clean electric guitar", "hand percussion"],
     ("sung", ["a powerful belting voice"], ["answered by a call-and-response choir"])),
    ("vocal", "barbershop", "Vocal / Barbershop Quartet", 120, "Ab major", "moderately extended", "loose and human", "harmonically led", "light low end",
     ["barbershop", "folk"], ["playful and carefree", "warm and nostalgic"], ["a wedding first dance"],
     ["a dry close-mic'd intimate sound", "a narrow mono-leaning image"],
     ["handclaps"],
     ("sung", ["a choir of many voices", "a clear bright voice"], ["layered in thick stacked harmonies", "answered by a call-and-response choir"])),
    ("pop", "boy_band", "Pop / Boy Band", 104, "G major", "simple diatonic", "machine-tight", "balanced", "solid bass weight",
     ["mainstream pop", "contemporary R&B"], ["romantic and longing", "tender and intimate"], ["a wedding first dance"],
     ["a clean modern polished mix", "a wide spacious stereo image"],
     ["punchy electronic drum machine", "acoustic guitar", "electric bass guitar", "analog synth pads"],
     ("sung", ["a smooth polished pop voice", "a high airy falsetto"], ["layered in thick stacked harmonies", "crooned smoothly"])),
    ("pop", "city_pop", "Pop / City Pop", 116, "A major", "chromatic / extended harmony", "machine-tight", "balanced", "solid bass weight",
     ["city pop", "disco"], ["warm and nostalgic", "spacious and weightless"], ["a long night drive", "a summer road trip"],
     ["a wide spacious stereo image", "warm analog tape saturation", "a shimmering high-end sheen"],
     ["warm Rhodes electric piano", "slap bass", "clean electric guitar", "analog synth pads", "acoustic drum kit"],
     ("sung", ["a clear bright voice"], ["crooned smoothly", "doubled with a close harmony"])),
    ("pop", "jpop", "Pop / J-Pop", 140, "E major", "moderately extended", "machine-tight", "drum-forward", "solid bass weight",
     ["j-pop", "indie pop"], ["bright and joyful", "euphoric and rushing"], ["a festival main stage"],
     ["a clean modern polished mix", "a loud heavily compressed master"],
     ["acoustic drum kit", "crunchy distorted electric guitar", "bright synth lead", "electric bass guitar", "grand piano"],
     ("sung", ["a clear bright voice"], ["belted out powerfully", "layered in thick stacked harmonies"])),
    ("pop", "easy_listening", "Pop / Easy Listening", 84, "C major", "moderately extended", "loose and human", "harmonically led", "light low end",
     ["lounge", "new age"], ["calm and meditative", "tender and intimate"], ["falling asleep and winding down", "a coffee shop afternoon"],
     ["a dry close-mic'd intimate sound", "a wide spacious stereo image"],
     ["grand piano", "flute", "string section", "brushed jazz drums", "harp"],
     ("sung", ["a light breathy voice"], ["sung softly and gently"])),
    ("electronic", "italo_disco", "Electronic / Italo-Disco", 126, "D minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["disco", "synth-pop"], ["euphoric and rushing", "warm and nostalgic"], ["a crowded dancefloor at peak hour"],
     ["a wide spacious stereo image", "long cavernous hall reverb", "warm analog tape saturation"],
     ["punchy electronic drum machine", "warm analog synth bass", "arpeggiated synthesizer", "bright synth lead"],
     ("sung", ["a clear bright voice"], ["crooned smoothly", "drenched in delay and reverb"])),
    ("electronic", "nu_disco", "Electronic / Nu-Disco", 118, "F# minor", "moderately extended", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["disco", "house"], ["playful and carefree", "sensual and smouldering"], ["a crowded dancefloor at peak hour"],
     ["a clean modern polished mix", "sidechain pumping compression"],
     ["punchy electronic drum machine", "slap bass", "clean electric guitar", "analog synth pads", "handclaps"],
     ("sung", ["a soulful gospel-trained voice"], ["crooned smoothly", "layered in thick stacked harmonies"])),
    ("electronic", "eurobeat", "Electronic / Eurobeat", 155, "B minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["trance", "synth-pop"], ["euphoric and rushing", "urgent and restless"], ["a long night drive", "a crowded dancefloor at peak hour"],
     ["a loud heavily compressed master", "a wide spacious stereo image"],
     ["punchy electronic drum machine", "warm analog synth bass", "arpeggiated synthesizer", "bright synth lead", "grand piano"],
     ("sung", ["a powerful belting voice"], ["belted out powerfully"])),
    ("electronic", "electropop", "Electronic / Electropop", 112, "C minor", "simple diatonic", "machine-tight", "balanced", "solid bass weight",
     ["synth-pop", "indie pop"], ["bittersweet", "confident and swaggering"], ["a long night drive"],
     ["a clean modern polished mix", "gentle detuning and chorus wobble"],
     ["punchy electronic drum machine", "warm analog synth bass", "arpeggiated synthesizer", "analog synth pads"],
     ("sung", ["a clear bright voice", "a heavily autotuned voice"], ["sung softly and gently", "layered in thick stacked harmonies"])),
    ("electronic", "folktronica", "Electronic / Folktronica", 100, "D major", "simple diatonic", "loose and human", "balanced", "moderate low end",
     ["downtempo", "indie folk"], ["hazy and drifting", "warm and nostalgic"], ["a slow lazy Sunday morning"],
     ["warm analog tape saturation", "a wide spacious stereo image"],
     ["fingerpicked acoustic guitar", "punchy electronic drum machine", "analog synth pads", "field recording ambience", "glockenspiel"],
     ("sung", ["a light breathy voice"], ["sung softly and gently", "drenched in delay and reverb"])),
    ("electronic", "dark_ambient", "Electronic / Dark Ambient", 60, "C minor", "chromatic / extended harmony", "loose and human", "harmonically led", "deep sub-heavy low end",
     ["ambient electronic", "cinematic score"], ["haunting and eerie", "dark and brooding", "claustrophobic and dense"], ["a tense chase scene"],
     ["heavy reverb drenching everything", "lo-fi bitcrushed digital artefacts"],
     ["analog synth pads", "reversed ambient swells", "field recording ambience", "solo cello"],
     ("instrumental", [], [])),
    ("electronic", "alternative_dance", "Electronic / Alternative Dance", 122, "A minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["alternative rock", "synth-pop"], ["mysterious and shadowy", "hypnotic and trance-like"], ["an after-hours club"],
     ["a wide spacious stereo image", "warm analog tape saturation"],
     ["punchy electronic drum machine", "warm analog synth bass", "clean electric guitar", "arpeggiated synthesizer"],
     ("sung", ["a deep resonant low-register voice"], ["sung in a flat deadpan monotone", "drenched in delay and reverb"])),
    ("electronic", "dance_punk", "Electronic / Dance-Punk", 138, "E minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["punk rock", "alternative rock"], ["energetic and driving", "angry and defiant"], ["a festival main stage"],
     ["a raw live-room recording", "gritty distortion and fuzz"],
     ["acoustic drum kit", "electric bass guitar", "crunchy distorted electric guitar", "punchy electronic drum machine"],
     ("sung", ["a nasal indie voice"], ["shouted and screamed", "sung in a flat deadpan monotone"])),
    ("hiphop", "grime", "Hip-Hop / Grime", 140, "F minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["drill", "trap"], ["urgent and restless", "menacing and aggressive"], ["an after-hours club"],
     ["a deep sub-heavy club mix", "a loud heavily compressed master"],
     ["808 drum machine", "punchy electronic drum machine", "bright synth lead", "deep sub bass"],
     ("spoken", ["a gritty rasping voice"], ["rapped in tight rhythmic flow", "answered by a call-and-response choir"])),
    ("hiphop", "industrial_hiphop", "Hip-Hop / Industrial", 130, "C minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["trap", "techno"], ["menacing and aggressive", "claustrophobic and dense"], ["a video game boss fight"],
     ["gritty distortion and fuzz", "a loud heavily compressed master", "lo-fi bitcrushed digital artefacts"],
     ["808 drum machine", "heavily distorted guitar", "deep sub bass", "reversed ambient swells"],
     ("spoken", ["a strained emotional voice"], ["shouted and screamed", "rapped in tight rhythmic flow"])),
    ("world", "flamenco", "World / Flamenco", 110, "A minor", "chromatic / extended harmony", "loose and human", "drum-forward", "moderate low end",
     ["world fusion", "latin pop"], ["gritty and raw", "romantic and longing"], ["a festival main stage"],
     ["a raw live-room recording", "a dry close-mic'd intimate sound"],
     ["fingerpicked acoustic guitar", "hand percussion", "handclaps", "upright double bass"],
     ("sung", ["a gritty rasping voice", "a strained emotional voice"], ["belted out powerfully", "answered by a call-and-response choir"])),
    ("world", "bachata", "World / Bachata", 128, "B minor", "moderately extended", "loose and human", "balanced", "solid bass weight",
     ["latin pop", "reggaeton"], ["romantic and longing", "sensual and smouldering"], ["a romantic dinner", "a beach party"],
     ["a clean modern polished mix", "a wide spacious stereo image"],
     ["clean electric guitar", "congas and bongos", "electric bass guitar", "hand percussion"],
     ("sung", ["a warm husky voice"], ["crooned smoothly"])),
    ("world", "bhangra", "World / Bhangra", 140, "D minor", "simple diatonic", "loose and human", "drum-forward", "deep sub-heavy low end",
     ["world fusion", "afrobeats"], ["euphoric and rushing", "playful and carefree"], ["a crowded dancefloor at peak hour", "a wedding first dance"],
     ["a loud heavily compressed master", "a clean modern polished mix"],
     ["hand percussion", "congas and bongos", "punchy electronic drum machine", "deep sub bass", "brass section"],
     ("sung", ["a powerful belting voice"], ["answered by a call-and-response choir", "belted out powerfully"])),
    ("world", "arabic_pop", "World / Arabic Pop", 100, "D minor", "chromatic / extended harmony", "loose and human", "drum-forward", "deep sub-heavy low end",
     ["latin pop", "contemporary R&B"], ["sensual and smouldering", "romantic and longing"], ["a romantic dinner"],
     ["a clean modern polished mix", "a wide spacious stereo image"],
     ["fingerpicked acoustic guitar", "808 drum machine", "string section", "hand percussion"],
     ("sung", ["a warm husky voice"], ["crooned smoothly", "layered in thick stacked harmonies"])),
    ("rock", "heartland", "Rock / Heartland", 128, "D major", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["classic rock", "americana"], ["hopeful and uplifting", "warm and nostalgic"], ["a summer road trip"],
     ["a raw live-room recording", "a wide spacious stereo image"],
     ["acoustic drum kit", "electric bass guitar", "clean electric guitar", "upright piano", "saxophone"],
     ("sung", ["a gritty rasping voice"], ["belted out powerfully"])),
    ("rock", "soft_rock", "Rock / Soft Rock", 96, "F major", "moderately extended", "loose and human", "harmonically led", "moderate low end",
     ["classic rock", "singer-songwriter acoustic"], ["tender and intimate", "bittersweet"], ["a slow lazy Sunday morning"],
     ["warm analog tape saturation", "a crisp studio multitrack production"],
     ["acoustic guitar", "grand piano", "electric bass guitar", "acoustic drum kit", "string section"],
     ("sung", ["a warm mid-range voice"], ["crooned smoothly", "doubled with a close harmony"])),
    ("rock", "yacht_rock", "Rock / Yacht Rock", 108, "Bb major", "chromatic / extended harmony", "machine-tight", "balanced", "solid bass weight",
     ["classic rock", "smooth jazz"], ["calm and meditative", "warm and nostalgic"], ["a summer road trip", "a cocktail lounge evening"],
     ["a crisp studio multitrack production", "a wide spacious stereo image"],
     ["warm Rhodes electric piano", "clean electric guitar", "electric bass guitar", "acoustic drum kit", "saxophone"],
     ("sung", ["a smooth polished pop voice"], ["crooned smoothly", "layered in thick stacked harmonies"])),
    ("rock", "space_rock", "Rock / Space Rock", 124, "E minor", "simple diatonic", "steady", "drum-forward", "solid bass weight",
     ["classic rock", "post-rock"], ["epic and cinematic", "spacious and weightless"], ["a long night drive"],
     ["a wide spacious stereo image", "long cavernous hall reverb", "warm analog tape saturation"],
     ["crunchy distorted electric guitar", "arpeggiated synthesizer", "electric bass guitar", "acoustic drum kit", "analog synth pads"],
     ("sung", ["a high airy falsetto"], ["drenched in delay and reverb", "belted out powerfully"])),
    ("rock", "emo", "Rock / Emo", 150, "C# minor", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["emo", "punk rock"], ["melancholy and wistful", "angry and defiant"], ["a film's emotional climax"],
     ["a raw live-room recording", "gritty distortion and fuzz"],
     ["acoustic drum kit", "crunchy distorted electric guitar", "electric bass guitar", "clean electric guitar"],
     ("sung", ["a strained emotional voice"], ["shouted and screamed", "sung with heavy vibrato"])),
    ("metal", "industrial_metal", "Metal / Industrial", 145, "E minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["heavy metal", "techno"], ["menacing and aggressive", "claustrophobic and dense"], ["a video game boss fight"],
     ["gritty distortion and fuzz", "a loud heavily compressed master", "lo-fi bitcrushed digital artefacts"],
     ["heavily distorted guitar", "808 drum machine", "acoustic drum kit", "analog synth pads", "orchestral timpani"],
     ("sung", ["a gritty rasping voice"], ["shouted and screamed"])),
    ("metal", "thrash_metal", "Metal / Thrash", 190, "E minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["heavy metal", "punk rock"], ["angry and defiant", "menacing and aggressive"], ["a video game boss fight"],
     ["a raw live-room recording", "gritty distortion and fuzz"],
     ["heavily distorted guitar", "acoustic drum kit", "electric bass guitar"],
     ("sung", ["a gritty rasping voice"], ["shouted and screamed"])),
    ("metal", "cyber_metal", "Metal / Cyber", 148, "F# minor", "moderately extended", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["heavy metal", "synthwave"], ["menacing and aggressive", "epic and cinematic"], ["a video game boss fight", "a tense chase scene"],
     ["a loud heavily compressed master", "a wide spacious stereo image", "gritty distortion and fuzz"],
     ["heavily distorted guitar", "808 drum machine", "bright synth lead", "analog synth pads", "string section"],
     ("sung", ["a strained emotional voice"], ["shouted and screamed", "rapped in tight rhythmic flow"])),
    ("gospel", "southern_gospel", "Gospel / Southern", 108, "G major", "simple diatonic", "loose and human", "balanced", "solid bass weight",
     ["gospel", "country"], ["hopeful and uplifting", "triumphant and soaring"], ["a wedding first dance"],
     ["a raw live-room recording", "warm analog tape saturation"],
     ["upright piano", "solo violin", "mandolin", "slide guitar", "acoustic drum kit"],
     ("sung", ["a soulful gospel-trained voice", "a choir of many voices"], ["answered by a call-and-response choir", "layered in thick stacked harmonies"])),
    ("country", "honky_tonk", "Country / Honky Tonk", 132, "A major", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["country", "americana"], ["playful and carefree", "gritty and raw"], ["a campfire singalong"],
     ["a raw live-room recording", "a narrow mono-leaning image"],
     ["slide guitar", "honky-tonk piano", "upright double bass", "acoustic drum kit", "solo violin"],
     ("sung", ["a warm husky voice"], ["crooned smoothly", "doubled with a close harmony"])),
    ("cinematic", "classical", "Cinematic / Classical Chamber", 92, "D major", "chromatic / extended harmony", "loose and human", "harmonically led", "light low end",
     ["string quartet", "classical orchestral"], ["reflective and quiet", "tender and intimate"], ["a funeral or memorial", "a romantic dinner"],
     ["long cavernous hall reverb", "a dry close-mic'd intimate sound"],
     ["solo violin", "solo cello", "string section", "harp", "grand piano"],
     ("instrumental", [], [])),
]
