"""Preset library, part 1.

Authoring rule: name the genre's SIGNATURE, not its ingredients.

Every genre uses drums, bass and a harmony instrument; listing those describes
nothing. What identifies drill is sliding 808s and skittering hi-hat triplets;
what identifies reggae is the offbeat guitar skank and one-drop drums. If a
descriptor could belong to twenty genres, it is wasting a slot.

These deliberately do NOT draw from songscribe/vocab/*.yaml. That vocabulary is
bounded because CLAP needs a fixed label set to score against - presets are
human-authored and have no such constraint. Imposing it produced presets that
could not name any genre's defining feature.

Name genres generally rather than by region unless the preset IS the regional
variant: "drill", not "UK drill". Regional flavour belongs in the node's
`extra` field, where the user can ask for it.

  (category, slug, display, bpm, key, harmony, feel, drums, low_end,
   genre, mood, scene, production, instruments, (presence, timbre, delivery))
"""

P = [
    # ------------------------------------------------------------------ hip-hop
    ("hiphop", "boom_bap", "Hip-Hop / Boom Bap", 92, "E minor", "moderately extended", "loose and human", "drum-forward", "solid bass weight",
     ["boom bap hip-hop"], ["confident and swaggering", "gritty and raw"], ["a long night drive"],
     ["dusty sample-based production", "filtered and low-passed", "SP-1200 grit"],
     ["swung dusty drum break", "cracked snare on the two and four", "walking upright bass sample",
      "chopped jazzy piano loop", "constant vinyl crackle"],
     ("spoken", ["warm mid-range voice"], ["rapped in a steady pocket flow", "ad-libs answering each line"])),
    ("hiphop", "lofi", "Hip-Hop / Lo-Fi Chillhop", 78, "Db major", "moderately extended", "loose and human", "drum-forward", "solid bass weight",
     ["lo-fi hip-hop", "chillhop"], ["laid-back and dreamy"], ["studying and late-night focus", "rainy-day headphones listening"],
     ["muddy low-passed bedroom mix", "tape wow and flutter", "everything slightly detuned"],
     ["soft thumping kick", "lazy brushed hi-hats behind the beat", "warm Rhodes loop with chorus wobble",
      "muted jazz guitar fills", "heavy vinyl crackle", "round sub bass"],
     ("wordless", ["soft androgynous voice"], ["hushed and half-spoken, low in the mix", "wordless mmm and ooh hums"])),
    ("hiphop", "trap", "Hip-Hop / Trap", 140, "F minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["trap"], ["menacing and aggressive"], ["an after-hours club"],
     ["heavily compressed and loud", "wide sub-bass", "sparse and spacious"],
     ["rolling hi-hat triplets and stutters", "booming 808 glides", "crisp layered clap snare",
      "dark bell melody", "sharp rimshot fills"],
     ("spoken", ["heavily autotuned voice"], ["drawled triplet flow", "stacked ad-lib layers"])),
    ("hiphop", "drill", "Hip-Hop / Drill", 144, "G minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["drill"], ["dark and menacing"], ["a long night drive"],
     ["cold and spacious mix", "lots of empty space", "deep clean sub"],
     ["sliding 808 bass glides", "skittering hi-hat triplets", "sparse rimshot snare with a half-time feel",
      "ominous four-note minor piano motif", "plucked dark strings"],
     ("spoken", ["deep resonant low-register voice"], ["laid-back drawled flow", "doubled on the last word of each bar"])),
    ("hiphop", "grime", "Hip-Hop / Grime", 140, "F minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["grime"], ["urgent and restless"], ["an after-hours club"],
     ["raw and aggressive", "low-budget punch", "sparse and clipped"],
     ["square-wave bass stabs", "eski-style clipped drums", "siren synth lead",
      "sharp snare on the three", "abrupt beat drops"],
     ("spoken", ["gritty rasping voice"], ["rapid clipped flow", "crowd-shout chorus"])),
    ("hiphop", "industrial_hiphop", "Hip-Hop / Industrial", 130, "C minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["industrial hip hop"], ["menacing and aggressive"], ["a video game boss fight"],
     ["clipped and overdriven", "dystopian atmosphere", "harsh and dense"],
     ["distorted overdriven 808s", "metallic percussion hits", "noise sweeps and risers",
      "harsh detuned synth stabs", "machine-like drum loop"],
     ("spoken", ["strained shouting voice"], ["barked and shouted delivery", "layered with growls"])),
    # --------------------------------------------------------------- soul / r&b
    ("soul", "neo_soul", "Soul / Neo-Soul", 86, "Eb major", "chromatic / extended harmony", "loose and human", "balanced", "solid bass weight",
     ["neo-soul", "contemporary R&B"], ["sensual and smouldering"], ["a romantic dinner", "a cocktail lounge evening"],
     ["warm analog, live-band feel", "intimate close-mic vocal"],
     ["warm Rhodes with slow chorus", "fingered electric bass sliding between notes",
      "loose drum pocket dragging behind the beat", "muted jazz guitar comping",
      "extended ninth and eleventh chords"],
     ("sung", ["warm husky voice"], ["crooned and melismatic", "thick stacked background harmonies"])),
    ("soul", "classic_soul", "Soul / Classic Motown", 112, "C major", "simple diatonic", "loose and human", "balanced", "solid bass weight",
     ["classic soul", "Motown"], ["bright and joyful"], ["a wedding first dance"],
     ["vintage mono-leaning mix", "recorded live in one room", "tape saturation"],
     ["driving tambourine on every backbeat", "melodic walking electric bass", "punchy horn section stabs",
      "Hammond organ pads", "vibraphone sparkle"],
     ("sung", ["powerful belting voice"], ["belted with full-throated power", "call-and-response backing trio"])),
    ("soul", "funk", "Soul / Funk", 108, "D minor", "moderately extended", "loose and human", "drum-forward", "solid bass weight",
     ["funk"], ["playful and carefree"], ["a crowded dancefloor at peak hour"],
     ["dry punchy drums", "live band in a room", "everything locked to the one"],
     ["syncopated slap and pop bass", "wah-wah clavinet", "tight sixteenth-note hi-hats",
      "stabbing horn section hits", "single-chord vamp"],
     ("sung", ["gritty rasping voice"], ["shouted and percussive", "grunts and hollers on the offbeats"])),
    ("gospel", "southern_gospel", "Gospel / Southern", 108, "G major", "simple diatonic", "loose and human", "balanced", "solid bass weight",
     ["southern gospel"], ["hopeful and uplifting"], ["a wedding first dance"],
     ["live congregation feel", "warm analog tape", "room ambience"],
     ["four-part close harmony", "rolling gospel piano runs", "Hammond organ swells",
      "handclaps on the backbeat", "a key change into the final chorus"],
     ("sung", ["soulful gospel-trained voice"], ["call-and-response with the choir", "improvised runs over the last chorus"])),
    # -------------------------------------------------------------------- pop
    ("pop", "anthem", "Pop / Modern Anthem", 124, "C major", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["mainstream pop"], ["euphoric and rushing"], ["a festival main stage", "a gym workout"],
     ["loud polished master", "heavy sidechain pump", "wide stereo chorus"],
     ["four-on-the-floor kick", "huge layered clap snare", "stacked supersaw chorus",
      "pitched vocal chop hook", "riser and silence before the drop"],
     ("sung", ["clear bright voice"], ["belted in the chorus, restrained in the verse", "octave-up double on the last chorus"])),
    ("pop", "synth_pop", "Pop / Synth-Pop", 118, "A minor", "simple diatonic", "machine-tight", "balanced", "solid bass weight",
     ["synth-pop"], ["bittersweet"], ["a long night drive"],
     ["gated reverb on the snare", "wide 1980s reverb", "analog warmth"],
     ["pulsing analog synth bass sequence", "drum machine with a huge gated snare",
      "arpeggiated synth figure", "bright monophonic lead", "glassy bell counter-melody"],
     ("sung", ["clear bright voice"], ["sung with cool restraint", "doubled an octave up in the chorus"])),
    ("pop", "dream_pop", "Pop / Dream Pop", 96, "E major", "moderately extended", "loose and human", "harmonically led", "moderate low end",
     ["dream pop", "shoegaze"], ["hazy and drifting"], ["falling asleep and winding down"],
     ["drowned in reverb", "hazy and low-passed", "vocals buried in the mix"],
     ["reverb-drenched tremolo guitar", "slow chorus and pitch wobble", "washed-out synth pads",
      "simple soft drum pattern", "reversed cymbal swells"],
     ("sung", ["light breathy voice"], ["sung softly, almost whispered", "words blurred into texture"])),
    ("pop", "kpop", "Pop / K-Pop", 110, "B minor", "moderately extended", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["k-pop"], ["confident and swaggering"], ["a festival main stage"],
     ["immaculate high-gloss production", "loud and transient-heavy", "dramatic transitions"],
     ["trap-influenced verse beat", "four-on-the-floor chorus", "stacked supersaw chorus",
      "chopped vocal hook", "a dramatic beat switch before the last chorus"],
     ("sung", ["clear bright voice"], ["rapped verse switching to a belted chorus", "four distinct voices trading lines"])),
    ("pop", "city_pop", "Pop / City Pop", 116, "A major", "chromatic / extended harmony", "machine-tight", "balanced", "solid bass weight",
     ["city pop"], ["warm and nostalgic"], ["a long night drive", "a summer road trip"],
     ["glossy 1980s studio polish", "wide stereo", "lush and layered"],
     ["slap bass with popped sixteenths", "chorused clean electric guitar", "electric piano comping",
      "gated drums with big room snare", "smooth saxophone fills"],
     ("sung", ["smooth polished voice"], ["crooned effortlessly", "lush layered harmonies on the hook"])),
    ("pop", "jpop", "Pop / J-Pop", 140, "E major", "moderately extended", "machine-tight", "drum-forward", "solid bass weight",
     ["j-pop"], ["bright and joyful"], ["a festival main stage"],
     ["dense loud mix", "everything bright and forward"],
     ["bright distorted guitars", "busy driving eighth-note bass", "fill-heavy energetic drums",
      "soaring chorus melody with a wide range", "orchestral string stabs"],
     ("sung", ["clear bright voice"], ["sung with emotional force in a high register", "layered chorus harmonies"])),
    ("pop", "boy_band", "Pop / Boy Band", 104, "G major", "simple diatonic", "machine-tight", "balanced", "solid bass weight",
     ["boy band pop"], ["romantic and longing"], ["a wedding first dance"],
     ["clean radio polish", "vocals front and centre"],
     ["finger snaps through the verse", "soft acoustic guitar", "sparse programmed beat",
      "a key change into the final chorus", "sustained synth pad bed"],
     ("sung", ["smooth polished voice"], ["solo verses trading between members", "five-part harmony stack on the chorus"])),
    ("pop", "easy_listening", "Pop / Easy Listening", 84, "C major", "moderately extended", "loose and human", "harmonically led", "light low end",
     ["easy listening", "lounge"], ["calm and meditative"], ["falling asleep and winding down", "a coffee shop afternoon"],
     ["gentle and warm", "very low dynamic range", "soft-edged"],
     ["softly brushed drums", "nylon-string guitar", "lush string pad", "breathy flute line", "vibraphone"],
     ("sung", ["light breathy voice"], ["sung gently and close to the mic"])),
    # ------------------------------------------------------------------- rock
    ("rock", "indie", "Rock / Indie", 132, "G major", "simple diatonic", "loose and human", "drum-forward", "moderate low end",
     ["indie rock"], ["bittersweet"], ["a summer road trip"],
     ["raw live-room recording", "slightly ragged and unpolished"],
     ["jangly clean electric guitar", "driving eighth-note bass", "live drums with a loose backbeat",
      "shouted group backing vocals", "a second guitar answering the vocal"],
     ("sung", ["nasal indie voice"], ["sung slightly off-pitch with feeling", "whole-band gang vocal on the hook"])),
    ("rock", "classic", "Rock / Classic 70s", 124, "A major", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["classic rock"], ["confident and swaggering"], ["a summer road trip"],
     ["analog tape saturation", "recorded live off the floor"],
     ["overdriven riff built on power chords", "Hammond organ underneath", "swung rock drums with heavy cymbals",
      "bluesy pentatonic guitar solo", "melodic bass fills between lines"],
     ("sung", ["gritty rasping voice"], ["belted at the top of the range", "wailing held notes"])),
    ("rock", "grunge", "Rock / Grunge", 118, "E minor", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["grunge"], ["angry and defiant"], ["a film's emotional climax"],
     ["blown-out and raw", "deliberately unpolished"],
     ["quiet clean verse exploding into a fuzz chorus", "sludgy detuned bass",
      "heavy pounding drums", "squealing feedback between sections", "drop-D power chords"],
     ("sung", ["rough untrained voice"], ["mumbled in the verse, screamed in the chorus"])),
    ("rock", "punk", "Rock / Punk", 168, "D major", "simple diatonic", "loose and human", "drum-forward", "moderate low end",
     ["punk rock"], ["angry and defiant"], ["a festival main stage"],
     ["fast raw and distorted", "recorded cheap and loud"],
     ["buzzsaw downstroke guitar", "relentless fast snare", "root-note eighth bass",
      "three chords and no solo", "count-in shouted at the top"],
     ("sung", ["rough untrained voice"], ["shouted rather than sung", "whole-band gang chorus"])),
    ("rock", "post_rock", "Rock / Post-Rock", 84, "D major", "simple diatonic", "steady", "balanced", "moderate low end",
     ["post-rock"], ["epic and cinematic"], ["a film's emotional climax"],
     ["enormous reverb", "wide dynamic build from near-silence to full volume"],
     ["tremolo-picked guitar", "delay-soaked clean arpeggio", "slow crescendo over several minutes",
      "cymbal swells building underneath", "strings entering at the peak"],
     ("instrumental", [], [])),
    ("rock", "metal", "Rock / Heavy Metal", 150, "E minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["heavy metal"], ["menacing and aggressive"], ["a video game boss fight"],
     ["tight modern and loud", "scooped guitar tone"],
     ["palm-muted gallop riff", "double-kick drum pattern", "twin guitar harmony lines",
      "shred solo with tapping", "crash accents on the riff turnarounds"],
     ("sung", ["gritty rasping voice"], ["snarled and shouted", "clean soaring chorus against harsh verses"])),
    ("rock", "emo", "Rock / Emo", 150, "C# minor", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["emo"], ["melancholy and wistful"], ["a film's emotional climax"],
     ["raw live-room recording", "guitars wide, vocals dry and forward"],
     ["twinkly clean arpeggiated guitar", "octave-chord riffing", "half-time chorus drop",
      "driving bass through the chorus", "sudden stop before the last line"],
     ("sung", ["strained emotional voice"], ["voice cracking at the peak", "shouted double on the final chorus"])),
    ("rock", "heartland", "Rock / Heartland", 128, "D major", "simple diatonic", "loose and human", "drum-forward", "solid bass weight",
     ["heartland rock"], ["hopeful and uplifting"], ["a summer road trip"],
     ["big live room", "wide anthemic reverb"],
     ["jangly open-chord guitar", "rolling piano eighths", "saxophone solo",
      "steady driving backbeat", "glockenspiel doubling the hook"],
     ("sung", ["gritty rasping voice"], ["belted with hoarse conviction", "crowd singalong on the chorus"])),
    ("rock", "soft_rock", "Rock / Soft Rock", 96, "F major", "moderately extended", "loose and human", "harmonically led", "moderate low end",
     ["soft rock"], ["tender and intimate"], ["a slow lazy Sunday morning"],
     ["warm analog tape", "smooth polished studio sound"],
     ["strummed acoustic guitar", "electric piano pad", "understated brushed drums",
      "melodic fretless bass", "string section on the final chorus"],
     ("sung", ["warm mid-range voice"], ["sung smoothly and close-mic'd", "close two-part harmony throughout"])),
    ("rock", "yacht_rock", "Rock / Yacht Rock", 108, "Bb major", "chromatic / extended harmony", "machine-tight", "balanced", "solid bass weight",
     ["yacht rock"], ["calm and meditative"], ["a summer road trip", "a cocktail lounge evening"],
     ["immaculate studio polish", "every part perfectly placed"],
     ["jazzy seventh and ninth chords", "chorused clean electric guitar", "smooth saxophone solo",
      "tight session-drummer pocket", "electric piano comping"],
     ("sung", ["smooth polished voice"], ["crooned effortlessly", "lush close harmonies"])),
    ("rock", "space_rock", "Rock / Space Rock", 124, "E minor", "simple diatonic", "steady", "drum-forward", "solid bass weight",
     ["space rock"], ["spacious and weightless"], ["a long night drive"],
     ["cavernous reverb and echo", "wide phased stereo"],
     ["phaser-swept guitar", "hypnotic motorik drum beat", "analog synth sweeps",
      "one-chord drone underneath", "long instrumental passages"],
     ("sung", ["distant heavily reverbed voice"], ["chanted and repetitive", "buried under delay"])),
    # ------------------------------------------------------------------ metal
    ("metal", "industrial_metal", "Metal / Industrial", 145, "E minor", "simple diatonic", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["industrial metal"], ["menacing and aggressive"], ["a video game boss fight"],
     ["clipped and mechanical", "cold and metallic"],
     ["mechanical programmed drum loop", "downtuned chugging riff", "sampled machinery and metal impacts",
      "harsh synth drone", "abrupt digital cuts"],
     ("sung", ["gritty rasping voice"], ["barked through a distortion pedal"])),
    ("metal", "thrash_metal", "Metal / Thrash", 190, "E minor", "simple diatonic", "machine-tight", "drum-forward", "solid bass weight",
     ["thrash metal"], ["angry and defiant"], ["a video game boss fight"],
     ["raw fast and loud", "trebly guitar tone"],
     ["relentless palm-muted downpicking", "double-kick blast sections", "chromatic riff runs",
      "frantic shred solo", "abrupt tempo changes"],
     ("sung", ["gritty rasping voice"], ["shouted staccato delivery", "gang-shouted chorus"])),
    ("metal", "cyber_metal", "Metal / Cyber", 148, "F# minor", "moderately extended", "machine-tight", "drum-forward", "deep sub-heavy low end",
     ["cyber metal"], ["epic and cinematic"], ["a video game boss fight", "a tense chase scene"],
     ["loud modern master", "neon synthetic sheen over heavy guitars"],
     ["downtuned riff under retro synth leads", "gated snare and double kick",
      "orchestral hits and cinematic strings", "arpeggiated synth between riffs", "sub drops on section changes"],
     ("sung", ["strained emotional voice"], ["rapped verse into a soaring clean chorus"])),
]
